### PR TITLE
Add Download Links To README

### PR DESCRIPTION
**Pull request by johannestheigen**
We kinda need download links for ruby, gem and bundler. So people can find the programs a lot easier. Without spending time searching for the programs.

### CODE REVIEW

**Comment by johannestheigen** [comment]
Bump

**Comment by andrgorr** [comment]
why would a normal user need to install this?

**Comment by AustinLMayes** [comment]
A user who does not have the knowledge to download these dependancies does not have the proper knowledge to run and contribute to this repository.
Also, bumping issues/pull requests is highly discouraged.

**Comment by johannestheigen** [comment]
Oh okay :P

**Pull request closed without merging**
