### PR TITLE
More explanation on readme

### PR DESCRIPTION
**Pull request by johannestheigen**
We download links for them.

Here Is The Links:
Download Links:

gem install bundle: http://bundler.io/v1.11/bundle_gem.html

bundle install: http://bundler.io/v1.11/bundle_install.html

middleman server: https://middlemanapp.com/basics/install/

### CODE REVIEW

**Comment by McFanta** [comment]
Www.//middlemanapp.com/basics/inst
gem install bundle:

**Comment by johannestheigen** [comment]
Woops the first link is broken. I'll fix that.

**Comment by johannestheigen** [comment]
Fixed

**Comment by johannestheigen** [comment]
I found some errors closing this and remaking a new one :P

**Pull request closed without merging**
