### PR TITLE
Add note to void region for water overflow

### PR DESCRIPTION
**Pull request by Palmidence**
Commit change hasn't been tested but shouldn't break anything

### CODE REVIEW

**Comment by Palmidence** [comment]
Requesting a reviewer, ALM wanted this to be documented for void and checks

**Comment by master00ofdsiware** [comment]
The commit would make the documentation misleading. The "ignored-blocks" attribute of the void region does not prevent water from flowing. What it does, is it tells the void region which blocks it should "ignore", or, in more practical terms, consider to be void/air.

The way to prevent water from flowing is two zone attributes, "water-rule" (for water), and "lava-rule" for water. This attribute's value can be as follows:

only-enter = water can only flow into the zone.
only-exit = water can only flow out of the zone.
no-flow = combination of the both (no flow occurs within the zone).

**Comment by Palmidence** [comment]
Could you post an XML sample of such?

**Comment by AustinLMayes** [comment]
@Palmidence It's just `<zone water-rule="" lava-rule="" ...` with the rules @master00ofdsiware explained above

**Comment by Palmidence** [comment]
👌

**Pull request closed without merging**
